{
    "bad_password": {
        "args": {"password": "INVALID_PASSWORD"},
        "exception": "pytan.api.session.AuthorizationError",
        "error_str": "Authentication Failed - Not Authenticated"
    },
    "bad_username": {
        "args": {"username": "INVALID_USERNAME"},
        "exception": "pytan.api.session.AuthorizationError",
        "error_str": "Authentication Failed - Incorrect User"
    },
    "bad_host_and_non_ssl_port": {
        "args": {"host": "127.0.0.1", "port": "4433"},
        "exception": "pytan.utils.HandlerError",
        "error_str": "Port test to.*FAILURE"
    }
}
